//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1:12/02/2018:Oftalmólego:Ojos cansados:Colirio:
        ///2:12/01/2019:Medico General:Gripe:Paracetamol y descanso domiciliario:
        ///1:06/10/2020:Oftalmólego:Ojos infectados:Colirio:
        ///1:20/10/20221:Médico General:Infección en herida externa brazo derecho:Desinfección con iodo:.
        /// </summary>
        internal static string fichaspacientes {
            get {
                return ResourceManager.GetString("fichaspacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Judit:Sandria Garcia:Avenida 8 Marzo, 153:38400:Puerto de la Cruz:12345678Z:1
        ///Jonay:Segura Andres:Calle La Quinta, 11:38300:La Orotava:00000000T:2
        ///Aithami:Gutierrez Gonzalez:Plaza Casañas, 5:38300:La Orotava:22620599F:3
        ///Ibrahim:Fatim:Calle Molina, 4::Puerto de la Cruz:21768220P:4
        ///Luis:Sanchez Felosio:Calle Meridiano, 12:38004:Santa Cruz de tenerife:79111401A:5
        ///Lisandro:Garcia Dolosa:Calle Montreal, 51:38300:Puerto de la Cruz:94747005T:6 .
        /// </summary>
        internal static string pacientes {
            get {
                return ResourceManager.GetString("pacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a admin:admin:administrador
        ///juan:j4:direccion
        ///isabel:i6:administrativo
        ///pepe:p4:personalsanitario
        ///laura:l5:personalsanitario
        ///susana:s6:administrador
        ///ramon:r5:administrativo
        ///ines:i4:personalsanitario.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
    }
}
